# Generated by Django 5.1.4 on 2024-12-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField()),
                ('entry_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_point', to='bus.busstop')),
                ('leave_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_point', to='bus.busstop')),
            ],
        ),
    ]
